### ISSUE TITLE
XML error with morningstar-uk

### ISSUE THREAD

**Issue by h1fisher** [joseballester/muFunds#21]
This has been working great for me for a long time so thanks so much!

However I found today that when I use morningstar-uk as the source I now return an error. It says:

Error on line 222: The prefix "xml" cannot be bound to any namespace other than its usual namespace; neither can the namespace for "xml" be bound to any prefix other than "xml". (line 106).

Any ideas how to fix this?

**Comment by rmetzger** [comment]
I'm having the same issue

**Comment by tairosonloa** [comment]
Same for morningstar-es. It seems like the XML response from then have changed

**Comment by joseballester** [comment]
Hi all! Thanks for reporting this issue. 

I just solved it via pull request #24 and deployed µFunds 2.4 to the G Suite Marketplace.

If the issue is not solved immediately, please wait up to 2 hours so the Google Apps Script cache, where HTML responses are saved, is regenerated. I just tried to load data from my own spreadsheet and most funds are working again.

Thanks again, and let me know if you find any other issue!
