### ISSUE TITLE
Unable to acces Australian Fund data using APIR or ISIN

### ISSUE THREAD

**Issue by No1squashfan** [joseballester/muFunds#27]
Mo matter what combination of option, id, or source that I use on Google Sheets, I just get error messages.
For example, trying to get the nav for Magellan Global:
=muFunds("nav","AU60MGE00068","morningstar") using the ISIN doesn't work - and I have tried "morningstar-au" as the source as well.
=muFunds("nav","MGE006AU","morningstar-au") using the APIR doesn't work - also changing the source.
The instructions also usggest using the Morningstar ID, but even as a daily user of morningstar, I can't find the secure ID - the AU website appears to be using the ASX number system for funds (eg Magellan Global is 15699.

Can someone give me a single example of the cell formula that works with common Australian funs?

**Comment by joseballester** [comment]
Thanks for opening this issue, @No1squashfan.

I just merged #28 that solves the issue, and pushed changes to a new version of µFunds, which should be already running. 

I tried some minutes ago and everything worked fine. Now I see morningstar.com.au is down, so I cannot test anymore. Please check it out and let me know if you find any issues.

**Comment by joseballester** [comment]
Just tried again and seems that it works. 

By the way, if I'm not wrong, there are two different funds:

| Name  | ISIN | APIR | ASX |
| ------------- | ------------- | ------------- | ------------- |
| Magellan Global  | AU60MGE00019  | MGE0001AU | 15699 |
| Magellan Infrastructure (Unhedged)  | AU60MGE00068  | MGE0006AU | 19879 |

Just noting it because you were using one's ISIN and APIR and the other's ASX.

**Comment by No1squashfan** [comment]
Thank you Jose. All fine now and in daily use.
