### ISSUE TITLE
Unable to retrieve NAV for iShares fund

### ISSUE THREAD

**Issue by nearlycossack** [joseballester/muFunds#4]
The Morningstar fund id is GB00B7QK1Y37. (iShares North American Eq Idx (UK) D Acc  (Blackrock))

I'm using =muFunds("nav", "GB00B7QK1Y37", "morningstar") but getting an error message : 
"Error: NAV is not available for this asset and source. Please try another data source (line 80)."

**Comment by joseballester** [comment]
Hi @nearlycossack, thank you for your feedback! Some funds are not compatible with the so-called Morningstar _generic mode_, so you should use a specific country-based data source instead. For example, you could use the function call `=muFunds("nav", "GB00B7QK1Y37", "morningstar-gb")`.

Please note that there is currently [an issue](https://github.com/joseballester/muFunds/issues/3) with the Morningstar UK data source that has already been solved, and should be pushed to the Google Sheets add-on store shortly (1-3 days).

**Comment by nearlycossack** [comment]
Thank you for your reply. Peter

**Comment by atanaskanchev** [comment]
Hi @joseballester I am still facing the same issue with version 2.2.
For example `http://quotes.morningstar.com/fund/c-header?t=F00000OJRT` doesn't always return NAV.

How about switching from `http://quotes.morningstar.com/fund/c-header?t=` to `http://www.morningstar.co.uk/uk/funds/snapshot/p_snapshot.aspx?id=F00000OJRT`

This gives a lot more info like trailing/annual returns etc.

Regards,
Atanas

**Comment by joseballester** [comment]
Hi @atanaskanchev!

As you say, the Morningstar generic quote (data source when using `morningstar` as the third argument) is not working for this fund and it does not return a NAV. That's why I suggested using the `morningstar-gb` data source instead, to use the UK snapshot page you're referring to.

Therefore, if you use `=muFunds("nav", "F00000OJRT", "morningstar-gb")` (or by ISIN: `=muFunds("nav", "GB00B84DY642", "morningstar-gb")`), a proper NAV should be returned.

Unfortunately, the data availability for each source is away from our hands, and sometimes it turns out that some sources work better than others. The generic mode (`morningstar`) is useful because you don't need to define a specific country and it works with a wide variety of funds.

Let me know if that works for you!
